### ISSUE TITLE
Add tests!

### ISSUE THREAD

**Issue by dmoll1974** [dmoll1974/targets-io#12]

**Comment by roydekleijn** [comment]
yes, because examples don't work. There seems to be no connection with graphite

20:34:20.646 [ERROR] i.g.m.GraphiteSender - Actor io.gatling.metrics.GraphiteSender@253c3b8b crashed on message Some(SendMetrics(Map(GraphitePath(List(Get_People)) -> MetricByStatus(Some(Metrics(46,3,25,7,11,19,23)),None,Some(Metrics(46,3,25,7,11,19,23))), GraphitePath(List(allRequests)) -> MetricByStatus(Some(Metrics(138,2,29,5,7,17,23)),None,Some(Metrics(138,2,29,5,7,17,23))), GraphitePath(List(Post_People)) -> MetricByStatus(Some(Metrics(46,2,29,4,6,13,24)),None,Some(Metrics(46,2,29,4,6,13,24))), GraphitePath(List(Hello_world)) -> MetricByStatus(Some(Metrics(46,2,10,4,5,7,9)),None,Some(Metrics(46,2,10,4,5,7,9)))),Map(GraphitePath(List(allUsers, users)) -> UsersBreakdown(1681,47,1500,180), GraphitePath(List(acceptanceTestScenario, users)) -> UsersBreakdown(1680,46,1500,180), GraphitePath(List(Targets-io_Keepalive, users)) -> UsersBreakdown(1,1,0,0))))
java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_66-internal]
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_66-internal]
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_66-internal]
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_66-internal]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_66-internal]
    at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_66-internal]
    at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_66-internal]
    at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_66-internal]
    at java.net.Socket.<init>(Socket.java:211) ~[na:1.8.0_66-internal]
    at io.gatling.metrics.sender.TcpSender.<init>(TcpSender.scala:27) ~[gatling-metrics-2.1.7.jar:2.1.7]
    at io.gatling.metrics.sender.MetricsSender$.newMetricsSender(MetricsSender.scala:26) ~[gatling-metrics-2.1.7.jar:2.1.7]
    at io.gatling.metrics.GraphiteSender.io$gatling$metrics$GraphiteSender$$sendMetricsToGraphite(GraphiteDataWriter.scala:143) ~[gatling-metrics-2.1.7.jar:2.1.7]
    at io.gatling.metrics.GraphiteSender$$anonfun$receive$1.applyOrElse(GraphiteDataWriter.scala:105) ~[gatling-metrics-2.1.7.jar:2.1.7]
    at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.12.jar:na]
    at io.gatling.core.akka.BaseActor.aroundReceive(BaseActor.scala:22) ~[gatling-core-2.1.7.jar:2.1.7]
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[akka-actor_2.11-2.3.12.jar:na]
    at akka.actor.ActorCell.invoke(ActorCell.scala:487) ~[akka-actor_2.11-2.3.12.jar:na]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) ~[akka-actor_2.11-2.3.12.jar:na]
    at akka.dispatch.Mailbox.run(Mailbox.scala:220) ~[akka-actor_2.11-2.3.12.jar:na]
