### ISSUE TITLE
InternetExplorer 11 compatibility

### ISSUE THREAD

**Issue by loganmzz** [dmoll1974/targets-io#35]
At least "testrun-summary" doesn't display correctly using Internet Explorer 11 :
![image](https://cloud.githubusercontent.com/assets/5030510/20135609/e2459908-a670-11e6-8a3c-b9fdd4f2f743.png)

Here is the JavaScript problem:
```
TypeError: L’objet ne gère pas la propriété ou la méthode « includes »
   at TestRunSummaryDirectiveController (http://<root>/modules/testruns/directives/testrun-summary.client.directive.js:24:5)
   at invoke (http://<root>/lib/angular/angular.min.js:41:306)
   at Anonymous function (http://<root>/lib/angular/angular.min.js:89:391)
   at m (http://<root>/lib/angular/angular.min.js:65:59)
   at Anonymous function (http://<root>/lib/angular/angular.min.js:76:459)
   at Anonymous function (http://<root>/lib/angular/angular.min.js:130:399)
   at m.prototype.$eval (http://<root>/lib/angular/angular.min.js:145:96)
   at m.prototype.$digest (http://<root>/lib/angular/angular.min.js:142:165)
   at m.prototype.$apply (http://<root>/lib/angular/angular.min.js:145:399)
   at l (http://<root>/lib/angular/angular.min.js:97:248)
```

**Comment by dmoll1974** [comment]
Hi Logan,

Unfortunately it is not my intention to support all browsers, I haven't got the time to do this. Please consider using an evergreen browser. Or create a pull request :-)

Cheers

Daniel

**Comment by loganmzz** [comment]
Can be easily fixed with a polyfill. Are you ok to add a polyfill library ?

**Comment by dmoll1974** [comment]
Sure, can you add it and create a pull request please?

Cheers!

**Comment by dmoll1974** [comment]
Improved layout issues
